In [ ]:
#na_values
#keep_default_na
#na_filter

In [1]:
import pandas as pd

In [11]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')
df

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,NaN,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,not available,NaN,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,NaN,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [13]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',na_values =["not available",'No value'])
df

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,NaN,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,NaN,NaN,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,NaN,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [16]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')
df

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,No value,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,not available,NaN,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,NaN,not available,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [17]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',na_values ={'Company':'No value','Ticker':'not available'})
df

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,NaN,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,not available,NaN,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,NaN,NaN,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [20]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')
df.head(10)

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,No value,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,not available,NaN,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,NaN,not available,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,NaN,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
5,6,CVS Health,NaN,Health Care,Health Care: Pharmacy and Other Services,yes,no,yes,no,0,...,249728.0,Karen S. Lynch,U.S.,Woonsocket,Rhode Island,https://www.cvshealth.com,Public,"Market value as of July 15, 2024.",73653.0,8/5/2024
6,7,Exxon Mobil,NaN,Energy,Petroleum Refining,yes,no,no,no,-4,...,376317.0,Darren W. Woods,U.S.,Spring,Texas,https://www.exxonmobil.com,Public,Excise taxes have been deducted. Market value ...,516824.0,8/5/2024
7,8,Alphabet,GOOGL,Technology,Internet Services and Retailing,yes,no,no,no,0,...,402392.0,Sundar Pichai,U.S.,Mountain View,California,https://www.abc.xyz,Public,"Market value as of July 15, 2024.",2315182.0,8/5/2024
8,9,McKesson,MCK,Health Care,Wholesalers: Health Care,yes,no,no,no,0,...,62320.0,Brian S. Tyler,U.S.,Irving,Texas,https://www.mckesson.com,Public,"Figures are for fiscal year ended March 31, 20...",75007.0,8/5/2024
9,10,Cencora,COR,Health Care,Wholesalers: Health Care,yes,no,no,yes,1,...,62558.7,Steven H. Collis,U.S.,Conshohocken,Pennsylvania,https://www.cencora.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",43758.0,8/5/2024

In [22]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',keep_default_na = True)
df.head(10)

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,No value,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,not available,NaN,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,NaN,not available,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,NaN,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
5,6,CVS Health,NaN,Health Care,Health Care: Pharmacy and Other Services,yes,no,yes,no,0,...,249728.0,Karen S. Lynch,U.S.,Woonsocket,Rhode Island,https://www.cvshealth.com,Public,"Market value as of July 15, 2024.",73653.0,8/5/2024
6,7,Exxon Mobil,NaN,Energy,Petroleum Refining,yes,no,no,no,-4,...,376317.0,Darren W. Woods,U.S.,Spring,Texas,https://www.exxonmobil.com,Public,Excise taxes have been deducted. Market value ...,516824.0,8/5/2024
7,8,Alphabet,GOOGL,Technology,Internet Services and Retailing,yes,no,no,no,0,...,402392.0,Sundar Pichai,U.S.,Mountain View,California,https://www.abc.xyz,Public,"Market value as of July 15, 2024.",2315182.0,8/5/2024
8,9,McKesson,MCK,Health Care,Wholesalers: Health Care,yes,no,no,no,0,...,62320.0,Brian S. Tyler,U.S.,Irving,Texas,https://www.mckesson.com,Public,"Figures are for fiscal year ended March 31, 20...",75007.0,8/5/2024
9,10,Cencora,COR,Health Care,Wholesalers: Health Care,yes,no,no,yes,1,...,62558.7,Steven H. Collis,U.S.,Conshohocken,Pennsylvania,https://www.cencora.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",43758.0,8/5/2024

In [23]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')
df.head(10)

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,Walmart,WMT,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,Walmart,WMT,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,Walmart,WMT,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Walmart,WMT,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
5,6,Walmart,WMT,Health Care,Health Care: Pharmacy and Other Services,yes,no,yes,no,0,...,249728.0,Karen S. Lynch,U.S.,Woonsocket,Rhode Island,https://www.cvshealth.com,Public,"Market value as of July 15, 2024.",73653.0,8/5/2024
6,7,Exxon Mobil,WMT,Energy,Petroleum Refining,yes,no,no,no,-4,...,376317.0,Darren W. Woods,U.S.,Spring,Texas,https://www.exxonmobil.com,Public,Excise taxes have been deducted. Market value ...,516824.0,8/5/2024
7,8,Alphabet,GOOGL,Technology,Internet Services and Retailing,yes,no,no,no,0,...,402392.0,Sundar Pichai,U.S.,Mountain View,California,https://www.abc.xyz,Public,"Market value as of July 15, 2024.",2315182.0,8/5/2024
8,9,McKesson,MCK,Health Care,Wholesalers: Health Care,yes,no,no,no,0,...,62320.0,Brian S. Tyler,U.S.,Irving,Texas,https://www.mckesson.com,Public,"Figures are for fiscal year ended March 31, 20...",75007.0,8/5/2024
9,10,Cencora,COR,Health Care,Wholesalers: Health Care,yes,no,no,yes,1,...,62558.7,Steven H. Collis,U.S.,Conshohocken,Pennsylvania,https://www.cencora.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",43758.0,8/5/2024

In [24]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',na_filter= True)
df.head(10)

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,Walmart,WMT,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,Walmart,WMT,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,Walmart,WMT,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Walmart,WMT,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
5,6,Walmart,WMT,Health Care,Health Care: Pharmacy and Other Services,yes,no,yes,no,0,...,249728.0,Karen S. Lynch,U.S.,Woonsocket,Rhode Island,https://www.cvshealth.com,Public,"Market value as of July 15, 2024.",73653.0,8/5/2024
6,7,Exxon Mobil,WMT,Energy,Petroleum Refining,yes,no,no,no,-4,...,376317.0,Darren W. Woods,U.S.,Spring,Texas,https://www.exxonmobil.com,Public,Excise taxes have been deducted. Market value ...,516824.0,8/5/2024
7,8,Alphabet,GOOGL,Technology,Internet Services and Retailing,yes,no,no,no,0,...,402392.0,Sundar Pichai,U.S.,Mountain View,California,https://www.abc.xyz,Public,"Market value as of July 15, 2024.",2315182.0,8/5/2024
8,9,McKesson,MCK,Health Care,Wholesalers: Health Care,yes,no,no,no,0,...,62320.0,Brian S. Tyler,U.S.,Irving,Texas,https://www.mckesson.com,Public,"Figures are for fiscal year ended March 31, 20...",75007.0,8/5/2024
9,10,Cencora,COR,Health Care,Wholesalers: Health Care,yes,no,no,yes,1,...,62558.7,Steven H. Collis,U.S.,Conshohocken,Pennsylvania,https://www.cencora.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",43758.0,8/5/2024