In [1]:
import pandas as pd

In [ ]:
#dropna--asis,how,thresh,inplace

In [2]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune_5.csv')
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,McKesson,MCK,219.6,Health Care,Wholesalers: Health Care

In [3]:
df.dropna()

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,McKesson,MCK,219.6,Health Care,Wholesalers: Health Care

In [4]:
df.dropna(axis=1)

,Rank,Company,Sector,Industry
0,1,Walmart,Retailing,General Merchandisers
1,2,Exxon Mobil,Retailing,Internet Services and Retailing
2,3,Alphabet,Technology,"Computers, Office Equipment"
3,4,McKesson,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,Energy,Petroleum Refining
7,8,Alphabet,Technology,Internet Services and Retailing
8,9,McKesson,Health Care,Wholesalers: Health Care

In [5]:
df.dropna(how='any')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,McKesson,MCK,219.6,Health Care,Wholesalers: Health Care

In [6]:
df.dropna(axis = 1,how='any')

,Rank,Company,Sector,Industry
0,1,Walmart,Retailing,General Merchandisers
1,2,Exxon Mobil,Retailing,Internet Services and Retailing
2,3,Alphabet,Technology,"Computers, Office Equipment"
3,4,McKesson,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,Energy,Petroleum Refining
7,8,Alphabet,Technology,Internet Services and Retailing
8,9,McKesson,Health Care,Wholesalers: Health Care

In [7]:
df.dropna(how='all')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,McKesson,MCK,219.6,Health Care,Wholesalers: Health Care

In [10]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune_5.csv')
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [11]:
df.dropna(thresh=2)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [12]:
df.dropna(thresh=4)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [13]:
df.dropna(subset=['Rank'])

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [14]:
df.dropna(subset=['Ticker'])

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [15]:
df.dropna(subset=['ProfitsPercentChange'])

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [17]:
df.dropna(inplace=True)
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing