In [1]:
import pandas as pd

In [3]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')

,1,2,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,32
0,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
1,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911,8/5/2024
2,2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565,8/5/2024
3,3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309,8/5/2024
4,4,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375,6/4/2024
997,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359,6/4/2024
998,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537,6/4/2024
999,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380,6/4/2024
1000,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798,6/4/2024

In [4]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv', header=1)

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [5]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')

,Unnamed: 0,Data,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,1,2,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,32
1,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
2,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911,8/5/2024
3,2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565,8/5/2024
4,3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375,6/4/2024
998,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359,6/4/2024
999,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537,6/4/2024
1000,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380,6/4/2024
1001,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798,6/4/2024

In [6]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',header=2)

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [7]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')

,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no.1,no.2,0,...,252399,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 2024. Market value as of July 15, 2024.",559911,8/5/2024
0,2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
1,3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
2,4,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
3,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
4,6,CVS Health,CVS,Health Care,Health Care: Pharmacy and Other Services,yes,no,yes,no,0,...,249728.0,Karen S. Lynch,U.S.,Woonsocket,Rhode Island,https://www.cvshealth.com,Public,"Market value as of July 15, 2024.",73653.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
995,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
996,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
997,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
998,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [8]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',header=None)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [9]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',header=None,prefix='Columns')

,Columns0,Columns1,Columns2,Columns3,Columns4,Columns5,Columns6,Columns7,Columns8,Columns9,...,Columns22,Columns23,Columns24,Columns25,Columns26,Columns27,Columns28,Columns29,Columns30,Columns31
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,...,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
996,997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,...,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
997,998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,...,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
998,999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,...,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
999,1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,...,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,Includes revenues from discontinued operations...,798.0,6/4/2024

In [13]:
pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv',names =['a','b'])

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,a,b
1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,no,no,no,yes,yes,yes,2100000,484852.8,648125.0,6.0,15511.0,32.8,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 2024. Market value as of July 15, 2024.",559911.0,8/5/2024
2,Amazon,AMZN,Retailing,Internet Services and Retailing,yes,no,no,no,0,no,no,no,yes,yes,no,1525000,1873675.8,574785.0,11.8,30425.0,NaN,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
3,Apple,AAPL,Technology,"Computers, Office Equipment",yes,no,no,no,1,yes,no,no,yes,yes,no,161000,2647973.8,383285.0,-2.8,96995.0,-2.8,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 2023. Market value as of July 15, 2024.",3594309.0,8/5/2024
4,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,yes,no,no,yes,yes,no,440000,456080.8,371622.0,14.6,22381.0,11.2,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
5,Berkshire Hathaway,BRKA,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,yes,no,no,yes,yes,no,396500,908919.7,364482.0,20.7,96223.0,NaN,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Allegiant Travel,ALGT,Transportation,Airlines,yes,no,no,yes,0,no,no,NaN,no,no,no,6686,1375.3,2509.9,9.0,117.6,4617.0,4869.4,Maurice J. Gallagher Jr.,U.S.,Las Vegas,Nevada,https://www.allegiant.com,Public,"Market value as of March 28, 2024.",1375.0,6/4/2024
997,Dropbox,DBX,Technology,Computer Software,yes,yes,no,no,0,no,no,NaN,no,no,no,2693,8358.8,2501.6,7.6,453.6,-18.0,2983.5,Andrew W. Houston,U.S.,San Francisco,California,https://www.dropbox.com,Public,"Market value as of March 28, 2024.",8359.0,6/4/2024
998,Exact Sciences,EXAS,Health Care,Pharmaceuticals,no,no,no,yes,0,no,no,NaN,no,no,no,6550,12536.5,2499.8,19.9,-204.1,NaN,6471.3,Kevin T. Conroy,U.S.,Madison,Wisconsin,https://www.exactsciences.com,Public,"Market value as of March 28, 2024.",12537.0,6/4/2024
999,BWX Technologies,BWXT,Aerospace & Defense,Aerospace & Defense,yes,no,no,yes,0,no,no,NaN,no,no,no,7800,9380.2,2496.3,11.8,245.8,3.2,2747.1,Rex D. Geveden,U.S.,Lynchburg,Virginia,https://www.bwxt.com,Public,"Market value as of March 28, 2024.",9380.0,6/4/2024
1000,Clear Channel Outdoor Hldgs.,CCO,Business Services,"Advertising, marketing",no,no,no,no,-10,no,yes,NaN,no,no,no,3900,798.1,2489.0,0.3,-310.9,NaN,4722.5,Scott R. Wells,U.S.,San Antonio,Texas,https://www.clearchanneloutdoor.com,Public,"Includes revenues from discontinued operations. Market value as of March 28, 2024.",798.0,6/4/2024