Loc =Access a group of rows & columns by labels or a boolean array
iloc=Integer location-based indexing

In [1]:
import pandas as pd

In [3]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\student_1.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72,35,0,33.6,23-10-2025
1,1,85,66,29,0,26.6,23-10-2026
2,8,183,64,0,0,23.3,23-10-2027
3,1,89,62,23,94,28.1,23-10-2028
4,0,137,60,35,168,43.1,23-10-2029
5,5,116,58,0,0,25.6,23-10-2030
6,3,78,56,32,88,31.0,23-10-2031
7,10,115,0,0,0,35.3,23-10-2032
8,2,197,70,45,543,30.5,23-10-2033
9,8,125,96,0,0,0.0,23-10-2034
10,4,110,92,0,0,37.6,23-10-2035
11,10,168,74,0,0,38.0,23-10-2036

In [4]:
df.loc[0]

Pregnancies               6
Glucose                 148
BloodPressure            72
SkinThickness            35
Insulin                   0
BMI                    33.6
date             23-10-2025
Name: 0, dtype: object

In [5]:
df.loc[4]

Pregnancies               0
Glucose                 137
BloodPressure            60
SkinThickness            35
Insulin                 168
BMI                    43.1
date             23-10-2029
Name: 4, dtype: object

In [7]:
df.loc[[0,1]]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72,35,0,33.6,23-10-2025
1,1,85,66,29,0,26.6,23-10-2026

In [8]:
df.loc[[2,5]]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
2,8,183,64,0,0,23.3,23-10-2027
5,5,116,58,0,0,25.6,23-10-2030

In [9]:
df.loc[4,'Glucose']

137

In [10]:
df.loc[0:3,'Glucose']

0    148
1     85
2    183
3     89
Name: Glucose, dtype: int64

In [11]:
df.loc[0:2,'BMI']

0    33.6
1    26.6
2    23.3
Name: BMI, dtype: float64

In [16]:
df.loc[df['Glucose']>150]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
2,8,183,64,0,0,23.3,23-10-2027
8,2,197,70,45,543,30.5,23-10-2033
11,10,168,74,0,0,38.0,23-10-2036

In [17]:
df.loc[df['Glucose']>150,['BMI']]

     BMI
2   23.3
8   30.5
11  38.0

In [18]:
df.iloc[0]

Pregnancies               6
Glucose                 148
BloodPressure            72
SkinThickness            35
Insulin                   0
BMI                    33.6
date             23-10-2025
Name: 0, dtype: object

In [19]:
df.iloc[[0]]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72,35,0,33.6,23-10-2025

In [20]:
df.iloc[:,0]

0      6
1      1
2      8
3      1
4      0
5      5
6      3
7     10
8      2
9      8
10     4
11    10
Name: Pregnancies, dtype: int64

In [21]:
df.iloc[[0,1]]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72,35,0,33.6,23-10-2025
1,1,85,66,29,0,26.6,23-10-2026

In [22]:
df.iloc[[True,False,True]]

IndexError: Boolean index has wrong length: 3 instead of 12