In [1]:
import pandas as pd

In [2]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune_5.csv')
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [3]:
df.fillna(2)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,2.0,Retailing,Internet Services and Retailing
2,3,Alphabet,2,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,2,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,2,2.0,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,2,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,2,2,2.0,2,2

In [4]:
df.fillna({'Company':'none','Ticker':0,'Sector':0})

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,0,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,0,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,0,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,0,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,none,0,NaN,0,NaN

In [5]:
df.fillna(method='ffill')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,32.8,Retailing,Internet Services and Retailing
2,3,Alphabet,WMT,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,WMT,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,WMT,11.2,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,WMT,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [6]:
df.fillna(method='pad')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,32.8,Retailing,Internet Services and Retailing
2,3,Alphabet,WMT,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,WMT,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,WMT,11.2,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,WMT,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [7]:
df.fillna(method='bfill')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,-2.8,Retailing,Internet Services and Retailing
2,3,Alphabet,WMT,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,WMT,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,WMT,101.1,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,WMT,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [9]:
df.fillna(method= 'ffill',axis=0)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,32.8,Retailing,Internet Services and Retailing
2,3,Alphabet,WMT,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,WMT,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,WMT,11.2,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,WMT,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [10]:
df.fillna(method= 'ffill',axis=1)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,WMT,Retailing,Internet Services and Retailing
2,3,Alphabet,Alphabet,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,McKesson,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,Cencora,Cencora,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,Costco Wholesale,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23,Technology,Internet Services and Retailing
8,9,9,9,9,9,9

In [11]:
df.fillna(method= 'bfill',axis=1)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,Retailing,Retailing,Internet Services and Retailing
2,3,Alphabet,-2.8,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,11.2,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,Financials,Financials,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,101.1,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [13]:
df.fillna(0, limit=2)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,0.0,Retailing,Internet Services and Retailing
2,3,Alphabet,0,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,0,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,0.0,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,0,NaN,NaN,0,0

In [16]:
df.fillna(method='ffill', limit=2)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,32.8,Retailing,Internet Services and Retailing
2,3,Alphabet,WMT,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,WMT,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,11.2,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing

In [19]:
df.fillna(5,inplace=True)
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,5.0,Retailing,Internet Services and Retailing
2,3,Alphabet,5,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,5,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,5,5.0,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,5,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,5,5,5.0,5,5

In [20]:
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,5.0,Retailing,Internet Services and Retailing
2,3,Alphabet,5,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,5,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,5,5.0,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,5,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,5,5,5.0,5,5