In [1]:
import pandas as pd

In [8]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\Pivot_table.csv')
df

     gener  Year  Budget  Rating%
0   Action  2008      20       45
1   Action  2010     200       67
2   Action  2010      45       34
3      ADV  2011      67       33
4      ADV  2012      89       66
5      ADV  2012      23       84
6  Comedy   2012     456       21
7  Comedy   2015      67       64

In [9]:
df.pivot_table(index = 'gener')

             Budget    Rating%         Year
gener
ADV       59.666667  61.000000  2011.666667
Action    88.333333  48.666667  2009.333333
Comedy   261.500000  42.500000  2013.500000

In [10]:
df.pivot_table(index = 'gener',columns ='Year')

        Budget                           Rating%
Year      2008   2010  2011   2012  2015    2008  2010  2011  2012  2015
gener
ADV        NaN    NaN  67.0   56.0   NaN     NaN   NaN  33.0  75.0   NaN
Action    20.0  122.5   NaN    NaN   NaN    45.0  50.5   NaN   NaN   NaN
Comedy     NaN    NaN   NaN  456.0  67.0     NaN   NaN   NaN  21.0  64.0

In [11]:
df.pivot_table(index = 'gener',columns ='Year',aggfunc = 'count')

        Budget                     Rating%
Year      2008 2010 2011 2012 2015    2008 2010 2011 2012 2015
gener
ADV        NaN  NaN  1.0  2.0  NaN     NaN  NaN  1.0  2.0  NaN
Action     1.0  2.0  NaN  NaN  NaN     1.0  2.0  NaN  NaN  NaN
Comedy     NaN  NaN  NaN  1.0  1.0     NaN  NaN  NaN  1.0  1.0

In [12]:
df.pivot_table(index = 'gener',columns ='Year',aggfunc = 'max')

        Budget                           Rating%
Year      2008   2010  2011   2012  2015    2008  2010  2011  2012  2015
gener
ADV        NaN    NaN  67.0   89.0   NaN     NaN   NaN  33.0  84.0   NaN
Action    20.0  200.0   NaN    NaN   NaN    45.0  67.0   NaN   NaN   NaN
Comedy     NaN    NaN   NaN  456.0  67.0     NaN   NaN   NaN  21.0  64.0

In [13]:
df.pivot_table(index = 'gener',columns ='Year',aggfunc = 'sum')

        Budget                           Rating%
Year      2008   2010  2011   2012  2015    2008   2010  2011   2012  2015
gener
ADV        NaN    NaN  67.0  112.0   NaN     NaN    NaN  33.0  150.0   NaN
Action    20.0  245.0   NaN    NaN   NaN    45.0  101.0   NaN    NaN   NaN
Comedy     NaN    NaN   NaN  456.0  67.0     NaN    NaN   NaN   21.0  64.0

In [15]:
df.pivot_table(index = 'gener',columns ='Year',fill_value =0)

        Budget                       Rating%
Year      2008   2010 2011 2012 2015    2008  2010 2011 2012 2015
gener
ADV          0    0.0   67   56    0       0   0.0   33   75    0
Action      20  122.5    0    0    0      45  50.5    0    0    0
Comedy       0    0.0    0  456   67       0   0.0    0   21   64

In [16]:
df.pivot_table(index = 'gener',columns ='Year',fill_value =0,margins= True)

        Budget                                          Rating%             \
Year      2008   2010 2011        2012 2015         All    2008  2010 2011
gener
ADV          0    0.0   67   56.000000    0   59.666667       0   0.0   33
Action      20  122.5    0    0.000000    0   88.333333      45  50.5    0
Comedy       0    0.0    0  456.000000   67  261.500000       0   0.0    0
All         20  122.5   67  189.333333   67  120.875000      45  50.5   33


Year    2012 2015        All
gener
ADV       75    0  61.000000
Action     0    0  48.666667
Comedy    21   64  42.500000
All       57   64  51.750000

In [17]:
df.pivot_table(index = 'gener',columns ='Year',fill_value =0,aggfunc = 'sum',margins= True)

        Budget                          Rating%
Year      2008 2010 2011 2012 2015  All    2008 2010 2011 2012 2015  All
gener
ADV          0    0   67  112    0  179       0    0   33  150    0  183
Action      20  245    0    0    0  265      45  101    0    0    0  146
Comedy       0    0    0  456   67  523       0    0    0   21   64   85
All         20  245   67  568   67  967      45  101   33  171   64  414