In [1]:
import pandas as pd

In [2]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune_5.csv')
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [4]:
df.replace(to_replace='Technology',value='Finance')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Finance,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Finance,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [5]:
df.replace('Technology','Finance')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Finance,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Finance,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [6]:
df.replace(32.8,32)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.0,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [7]:
df.replace([1,2,3,4,5,6,7,8,9],0)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,0,Walmart,WMT,32.8,Retailing,General Merchandisers
1,0,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,0,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,0,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,0,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,0,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,0,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,0,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,0,NaN,NaN,NaN,NaN,NaN

In [8]:
df.replace([1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18])

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,10,Walmart,WMT,32.8,Retailing,General Merchandisers
1,11,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,12,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,13,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,14,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,15,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,16,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,17,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,18,NaN,NaN,NaN,NaN,NaN

In [9]:
df.replace({'Sector':'Technology'},'none')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,none,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,none,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [11]:
df.replace({'Sector':'Technology','ProfitsPercentChange':32.8},'none')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,none,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,none,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23,none,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [12]:
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [13]:
df.replace('[A-Za-z]',0)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [14]:
df.replace('[A-Za-z]',0,regex=True)

   Rank  Company  Ticker  ProfitsPercentChange  Sector  Industry
0     1      0.0     0.0                  32.8     0.0       0.0
1     2      0.0     0.0                   NaN     0.0       0.0
2     3      0.0     NaN                  -2.8     0.0       0.0
3     4      0.0     NaN                  11.2     0.0       0.0
4     5      0.0     NaN                   NaN     0.0       0.0
5     6      0.0     NaN                 101.1     0.0       0.0
6     7      0.0     0.0                 -35.4     0.0       0.0
7     8      0.0     0.0                  23.0     0.0       0.0
8     9      NaN     NaN                   NaN     NaN       NaN

In [16]:
df.replace({'Sector':'[A-za-z]'},0,regex=True)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,0.0,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,0.0,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,0.0,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,0.0,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,0.0,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,0.0,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,0.0,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,0.0,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [18]:
df.replace('Technology',method='bfill')

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Health Care,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,NaN,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [21]:
df.replace(23.0,method='bfill',limit=1)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,NaN,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [24]:
df.replace(23.0,method='bfill',limit=2)

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,100.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [22]:
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,23.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN

In [23]:
df.replace(23.0,100,inplace=True)
df

,Rank,Company,Ticker,ProfitsPercentChange,Sector,Industry
0,1,Walmart,WMT,32.8,Retailing,General Merchandisers
1,2,Exxon Mobil,WMT,NaN,Retailing,Internet Services and Retailing
2,3,Alphabet,NaN,-2.8,Technology,"Computers, Office Equipment"
3,4,McKesson,NaN,11.2,Health Care,Health Care: Insurance and Managed Care
4,5,Cencora,NaN,NaN,Financials,Insurance: Property and Casualty (Stock)
5,6,Costco Wholesale,NaN,101.1,Health Care,Health Care: Pharmacy and Other Services
6,7,Exxon Mobil,WMT,-35.4,Energy,Petroleum Refining
7,8,Alphabet,GOOGL,100.0,Technology,Internet Services and Retailing
8,9,NaN,NaN,NaN,NaN,NaN