In [1]:
import pandas as pd

In [2]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\Pivot_table.csv')
df

     gener  Year  Budget  Rating%
0   Action  2008      20       45
1   Action  2010     200       67
2   Action  2010      45       34
3      ADV  2011      67       33
4      ADV  2012      89       66
5      ADV  2012      23       84
6  Comedy   2012     456       21
7  Comedy   2015      67       64

In [3]:
pd.melt(df)

   variable    value
0     gener   Action
1     gener   Action
2     gener   Action
3     gener      ADV
4     gener      ADV
5     gener      ADV
6     gener  Comedy
7     gener  Comedy
8      Year     2008
9      Year     2010
10     Year     2010
11     Year     2011
12     Year     2012
13     Year     2012
14     Year     2012
15     Year     2015
16   Budget       20
17   Budget      200
18   Budget       45
19   Budget       67
20   Budget       89
21   Budget       23
22   Budget      456
23   Budget       67
24  Rating%       45
25  Rating%       67
26  Rating%       34
27  Rating%       33
28  Rating%       66
29  Rating%       84
30  Rating%       21
31  Rating%       64

In [5]:
pd.melt(df,id_vars =['gener'])

      gener variable  value
0    Action     Year   2008
1    Action     Year   2010
2    Action     Year   2010
3       ADV     Year   2011
4       ADV     Year   2012
5       ADV     Year   2012
6   Comedy      Year   2012
7   Comedy      Year   2015
8    Action   Budget     20
9    Action   Budget    200
10   Action   Budget     45
11      ADV   Budget     67
12      ADV   Budget     89
13      ADV   Budget     23
14  Comedy    Budget    456
15  Comedy    Budget     67
16   Action  Rating%     45
17   Action  Rating%     67
18   Action  Rating%     34
19      ADV  Rating%     33
20      ADV  Rating%     66
21      ADV  Rating%     84
22  Comedy   Rating%     21
23  Comedy   Rating%     64

In [6]:
pd.melt(df,id_vars =['Year'])

    Year variable    value
0   2008    gener   Action
1   2010    gener   Action
2   2010    gener   Action
3   2011    gener      ADV
4   2012    gener      ADV
5   2012    gener      ADV
6   2012    gener  Comedy
7   2015    gener  Comedy
8   2008   Budget       20
9   2010   Budget      200
10  2010   Budget       45
11  2011   Budget       67
12  2012   Budget       89
13  2012   Budget       23
14  2012   Budget      456
15  2015   Budget       67
16  2008  Rating%       45
17  2010  Rating%       67
18  2010  Rating%       34
19  2011  Rating%       33
20  2012  Rating%       66
21  2012  Rating%       84
22  2012  Rating%       21
23  2015  Rating%       64

In [7]:
pd.melt(df,id_vars =['Year'], value_vars = ['gener'])

   Year variable    value
0  2008    gener   Action
1  2010    gener   Action
2  2010    gener   Action
3  2011    gener      ADV
4  2012    gener      ADV
5  2012    gener      ADV
6  2012    gener  Comedy
7  2015    gener  Comedy

In [8]:
pd.melt(df,id_vars =['Year'], value_vars = ['Rating%'])

   Year variable  value
0  2008  Rating%     45
1  2010  Rating%     67
2  2010  Rating%     34
3  2011  Rating%     33
4  2012  Rating%     66
5  2012  Rating%     84
6  2012  Rating%     21
7  2015  Rating%     64

In [9]:
pd.melt(df,id_vars =['Year'], value_vars = ['Rating%'],var_name = 'Category')

   Year Category  value
0  2008  Rating%     45
1  2010  Rating%     67
2  2010  Rating%     34
3  2011  Rating%     33
4  2012  Rating%     66
5  2012  Rating%     84
6  2012  Rating%     21
7  2015  Rating%     64

In [10]:
pd.melt(df,id_vars =['Year'], value_vars = ['Rating%'],var_name = 'Category',value_name = 'Data')

   Year Category  Data
0  2008  Rating%    45
1  2010  Rating%    67
2  2010  Rating%    34
3  2011  Rating%    33
4  2012  Rating%    66
5  2012  Rating%    84
6  2012  Rating%    21
7  2015  Rating%    64