In [1]:
import pandas as pd

In [11]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\student_1.csv')
df

    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI Class
0             6      148             72             35        0  33.6     A
1             1       85             66             29        0  26.6     B
2             8      183             64              0        0  23.3     C
3             1       89             62             23       94  28.1     D
4             0      137             60             35      168  43.1     E
5             5      116             58              0        0  25.6     F
6             3       78             56             32       88  31.0     I
7            10      115              0              0        0  35.3     J
8             2      197             70             45      543  30.5     K
9             8      125             96              0        0   0.0     L
10            4      110             92              0        0  37.6     M
11           10      168             74              0        0  38.0     N

In [6]:
gr=df.groupby(by = 'Pregnancies')
gr

In [7]:
gr.groups

{0: [4], 1: [1, 3], 2: [8], 3: [6], 4: [10], 5: [5], 6: [0], 8: [2, 9], 10: [7, 11]}

In [12]:
df.groupby(['Pregnancies','Class']).groups

{(0, 'E'): [4], (1, 'B'): [1], (1, 'D'): [3], (2, 'K'): [8], (3, 'I'): [6], (4, 'M'): [10], (5, 'F'): [5], (6, 'A'): [0], (8, 'C'): [2], (8, 'L'): [9], (10, 'J'): [7], (10, 'N'): [11]}

In [13]:
for Pregnancies, df_1 in gr:
    print(Pregnancies)
    print(df_1)

0
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
4            0      137             60             35      168  43.1
1
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
1            1       85             66             29        0  26.6
3            1       89             62             23       94  28.1
2
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
8            2      197             70             45      543  30.5
3
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
6            3       78             56             32       88  31.0
4
    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
10            4      110             92              0        0  37.6
5
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
5            5      116             58              0        0  25.6
6
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
0            6      148             72             35        0  33.6
8
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
2            8      183             64              0        0  23.3
9            8      125             96              0        0   0.0
10
    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
7            10      115              0              0        0  35.3
11           10      168             74              0        0  38.0

In [15]:
dict(list(gr))

{0:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 4            0      137             60             35      168  43.1,
 1:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 1            1       85             66             29        0  26.6
 3            1       89             62             23       94  28.1,
 2:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 8            2      197             70             45      543  30.5,
 3:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 6            3       78             56             32       88  31.0,
 4:     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 10            4      110             92              0        0  37.6,
 5:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 5            5      116             58              0        0  25.6,
 6:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 0            6      148             72             35        0  33.6,
 8:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 2            8      183             64              0        0  23.3
 9            8      125             96              0        0   0.0,
 10:     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
 7            10      115              0              0        0  35.3
 11           10      168             74              0        0  38.0}

In [20]:
gr1 = df.groupby('Pregnancies').get_group(1)
gr1

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI Class
1            1       85             66             29        0  26.6     B
3            1       89             62             23       94  28.1     D

In [21]:
gr1 = df.groupby('Class').get_group('A')
gr1

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI Class
0            6      148             72             35        0  33.6     A

In [22]:
gr.sum()

             Glucose  BloodPressure  SkinThickness  Insulin   BMI
Pregnancies
0                137             60             35      168  43.1
1                174            128             52       94  54.7
2                197             70             45      543  30.5
3                 78             56             32       88  31.0
4                110             92              0        0  37.6
5                116             58              0        0  25.6
6                148             72             35        0  33.6
8                308            160              0        0  23.3
10               283             74              0        0  73.3

In [23]:
gr.mean()

             Glucose  BloodPressure  SkinThickness  Insulin    BMI
Pregnancies
0              137.0           60.0           35.0    168.0  43.10
1               87.0           64.0           26.0     47.0  27.35
2              197.0           70.0           45.0    543.0  30.50
3               78.0           56.0           32.0     88.0  31.00
4              110.0           92.0            0.0      0.0  37.60
5              116.0           58.0            0.0      0.0  25.60
6              148.0           72.0           35.0      0.0  33.60
8              154.0           80.0            0.0      0.0  11.65
10             141.5           37.0            0.0      0.0  36.65

In [24]:
gr.describe()

            Glucose                                                         \
              count   mean        std    min     25%    50%     75%    max
Pregnancies
0               1.0  137.0        NaN  137.0  137.00  137.0  137.00  137.0
1               2.0   87.0   2.828427   85.0   86.00   87.0   88.00   89.0
2               1.0  197.0        NaN  197.0  197.00  197.0  197.00  197.0
3               1.0   78.0        NaN   78.0   78.00   78.0   78.00   78.0
4               1.0  110.0        NaN  110.0  110.00  110.0  110.00  110.0
5               1.0  116.0        NaN  116.0  116.00  116.0  116.00  116.0
6               1.0  148.0        NaN  148.0  148.00  148.0  148.00  148.0
8               2.0  154.0  41.012193  125.0  139.50  154.0  168.50  183.0
10              2.0  141.5  37.476659  115.0  128.25  141.5  154.75  168.0

            BloodPressure        ... Insulin          BMI                    \
                    count  mean  ...     75%    max count   mean        std
Pregnancies                      ...
0                     1.0  60.0  ...   168.0  168.0   1.0  43.10        NaN
1                     2.0  64.0  ...    70.5   94.0   2.0  27.35   1.060660
2                     1.0  70.0  ...   543.0  543.0   1.0  30.50        NaN
3                     1.0  56.0  ...    88.0   88.0   1.0  31.00        NaN
4                     1.0  92.0  ...     0.0    0.0   1.0  37.60        NaN
5                     1.0  58.0  ...     0.0    0.0   1.0  25.60        NaN
6                     1.0  72.0  ...     0.0    0.0   1.0  33.60        NaN
8                     2.0  80.0  ...     0.0    0.0   2.0  11.65  16.475588
10                    2.0  37.0  ...     0.0    0.0   2.0  36.65   1.909188


              min     25%    50%     75%   max
Pregnancies
0            43.1  43.100  43.10  43.100  43.1
1            26.6  26.975  27.35  27.725  28.1
2            30.5  30.500  30.50  30.500  30.5
3            31.0  31.000  31.00  31.000  31.0
4            37.6  37.600  37.60  37.600  37.6
5            25.6  25.600  25.60  25.600  25.6
6            33.6  33.600  33.60  33.600  33.6
8             0.0   5.825  11.65  17.475  23.3
10           35.3  35.975  36.65  37.325  38.0

[9 rows x 40 columns]

In [25]:
gr.agg(['sum','max','mean'])

            Glucose             BloodPressure          SkinThickness           \
                sum  max   mean           sum max mean           sum max mean
Pregnancies
0               137  137  137.0            60  60   60            35  35   35
1               174   89   87.0           128  66   64            52  29   26
2               197  197  197.0            70  70   70            45  45   45
3                78   78   78.0            56  56   56            32  32   32
4               110  110  110.0            92  92   92             0   0    0
5               116  116  116.0            58  58   58             0   0    0
6               148  148  148.0            72  72   72            35  35   35
8               308  183  154.0           160  96   80             0   0    0
10              283  168  141.5            74  74   37             0   0    0

            Insulin             BMI
                sum  max mean   sum   max   mean
Pregnancies
0               168  168  168  43.1  43.1  43.10
1                94   94   47  54.7  28.1  27.35
2               543  543  543  30.5  30.5  30.50
3                88   88   88  31.0  31.0  31.00
4                 0    0    0  37.6  37.6  37.60
5                 0    0    0  25.6  25.6  25.60
6                 0    0    0  33.6  33.6  33.60
8                 0    0    0  23.3  23.3  11.65
10                0    0    0  73.3  38.0  36.65