In [1]:
import pandas as pd

In [6]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\student.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72.0,35,0,33.6,23-10-2025
1,1,85,66.0,29,0,26.6,23-10-2026
2,8,183,64.0,0,0,23.3,23-10-2027
3,1,89,NaN,23,94,28.1,23-10-2028
4,0,137,NaN,35,168,43.1,23-10-2029
5,5,116,NaN,0,0,25.6,23-10-2030
6,3,78,NaN,32,88,31.0,23-10-2031
7,10,115,0.0,0,0,35.3,23-10-2032
8,2,197,70.0,45,543,30.5,23-10-2033
9,8,125,96.0,0,0,0.0,23-10-2034
10,4,110,92.0,0,0,37.6,23-10-2035
11,10,168,74.0,0,0,38.0,23-10-2036

In [7]:
df.interpolate()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72.0,35,0,33.6,23-10-2025
1,1,85,66.0,29,0,26.6,23-10-2026
2,8,183,64.0,0,0,23.3,23-10-2027
3,1,89,51.2,23,94,28.1,23-10-2028
4,0,137,38.4,35,168,43.1,23-10-2029
5,5,116,25.6,0,0,25.6,23-10-2030
6,3,78,12.8,32,88,31.0,23-10-2031
7,10,115,0.0,0,0,35.3,23-10-2032
8,2,197,70.0,45,543,30.5,23-10-2033
9,8,125,96.0,0,0,0.0,23-10-2034
10,4,110,92.0,0,0,37.6,23-10-2035
11,10,168,74.0,0,0,38.0,23-10-2036

In [8]:
df.interpolate(method='linear')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72.0,35,0,33.6,23-10-2025
1,1,85,66.0,29,0,26.6,23-10-2026
2,8,183,64.0,0,0,23.3,23-10-2027
3,1,89,51.2,23,94,28.1,23-10-2028
4,0,137,38.4,35,168,43.1,23-10-2029
5,5,116,25.6,0,0,25.6,23-10-2030
6,3,78,12.8,32,88,31.0,23-10-2031
7,10,115,0.0,0,0,35.3,23-10-2032
8,2,197,70.0,45,543,30.5,23-10-2033
9,8,125,96.0,0,0,0.0,23-10-2034
10,4,110,92.0,0,0,37.6,23-10-2035
11,10,168,74.0,0,0,38.0,23-10-2036

In [9]:
df.interpolate(method='time')

ValueError: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex

In [12]:
type(df.date[0])

str

In [13]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\student.csv',parse_dates=['date'])
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,date
0,6,148,72.0,35,0,33.6,2025-10-23
1,1,85,66.0,29,0,26.6,2026-10-23
2,8,183,64.0,0,0,23.3,2027-10-23
3,1,89,NaN,23,94,28.1,2028-10-23
4,0,137,NaN,35,168,43.1,2029-10-23
5,5,116,NaN,0,0,25.6,2030-10-23
6,3,78,NaN,32,88,31.0,2031-10-23
7,10,115,0.0,0,0,35.3,2032-10-23
8,2,197,70.0,45,543,30.5,2033-10-23
9,8,125,96.0,0,0,0.0,2034-10-23
10,4,110,92.0,0,0,37.6,2035-10-23
11,10,168,74.0,0,0,38.0,2036-10-23

In [14]:
type(df.date[0])

pandas._libs.tslibs.timestamps.Timestamp

In [15]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\student.csv',parse_dates=['date'],index_col='date')
df

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89            NaN             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78            NaN             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [16]:
df.interpolate(method='time')

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148      72.000000             35        0  33.6
2026-10-23            1       85      66.000000             29        0  26.6
2027-10-23            8      183      64.000000              0        0  23.3
2028-10-23            1       89      51.178982             23       94  28.1
2029-10-23            0      137      38.392994             35      168  43.1
2030-10-23            5      116      25.607006              0        0  25.6
2031-10-23            3       78      12.821018             32       88  31.0
2032-10-23           10      115       0.000000              0        0  35.3
2033-10-23            2      197      70.000000             45      543  30.5
2034-10-23            8      125      96.000000              0        0   0.0
2035-10-23            4      110      92.000000              0        0  37.6
2036-10-23           10      168      74.000000              0        0  38.0

In [17]:
df.interpolate(method='index')

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148      72.000000             35        0  33.6
2026-10-23            1       85      66.000000             29        0  26.6
2027-10-23            8      183      64.000000              0        0  23.3
2028-10-23            1       89      51.178982             23       94  28.1
2029-10-23            0      137      38.392994             35      168  43.1
2030-10-23            5      116      25.607006              0        0  25.6
2031-10-23            3       78      12.821018             32       88  31.0
2032-10-23           10      115       0.000000              0        0  35.3
2033-10-23            2      197      70.000000             45      543  30.5
2034-10-23            8      125      96.000000              0        0   0.0
2035-10-23            4      110      92.000000              0        0  37.6
2036-10-23           10      168      74.000000              0        0  38.0

In [18]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\student.csv',parse_dates=['date'],index_col='Pregnancies')
df

             Glucose  BloodPressure  SkinThickness  Insulin   BMI       date
Pregnancies
6                148           72.0             35        0  33.6 2025-10-23
1                 85           66.0             29        0  26.6 2026-10-23
8                183           64.0              0        0  23.3 2027-10-23
1                 89            NaN             23       94  28.1 2028-10-23
0                137            NaN             35      168  43.1 2029-10-23
5                116            NaN              0        0  25.6 2030-10-23
3                 78            NaN             32       88  31.0 2031-10-23
10               115            0.0              0        0  35.3 2032-10-23
2                197           70.0             45      543  30.5 2033-10-23
8                125           96.0              0        0   0.0 2034-10-23
4                110           92.0              0        0  37.6 2035-10-23
10               168           74.0              0        0  38.0 2036-10-23

In [19]:
df.interpolate(method='index')

             Glucose  BloodPressure  SkinThickness  Insulin   BMI       date
Pregnancies
6                148           72.0             35        0  33.6 2025-10-23
1                 85           66.0             29        0  26.6 2026-10-23
8                183           64.0              0        0  23.3 2027-10-23
1                 89           66.0             23       94  28.1 2028-10-23
0                137           66.0             35      168  43.1 2029-10-23
5                116           82.0              0        0  25.6 2030-10-23
3                 78           81.0             32       88  31.0 2031-10-23
10               115            0.0              0        0  35.3 2032-10-23
2                197           70.0             45      543  30.5 2033-10-23
8                125           96.0              0        0   0.0 2034-10-23
4                110           92.0              0        0  37.6 2035-10-23
10               168           74.0              0        0  38.0 2036-10-23

In [20]:
df.interpolate(method='nearest')

             Glucose  BloodPressure  SkinThickness  Insulin   BMI       date
Pregnancies
6                148           72.0             35        0  33.6 2025-10-23
1                 85           66.0             29        0  26.6 2026-10-23
8                183           64.0              0        0  23.3 2027-10-23
1                 89           66.0             23       94  28.1 2028-10-23
0                137            NaN             35      168  43.1 2029-10-23
5                116           92.0              0        0  25.6 2030-10-23
3                 78           70.0             32       88  31.0 2031-10-23
10               115            0.0              0        0  35.3 2032-10-23
2                197           70.0             45      543  30.5 2033-10-23
8                125           96.0              0        0   0.0 2034-10-23
4                110           92.0              0        0  37.6 2035-10-23
10               168           74.0              0        0  38.0 2036-10-23

In [21]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\student.csv',parse_dates=['date'],index_col='date')
df

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89            NaN             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78            NaN             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [22]:
df.interpolate(method='polynomial',order=1)

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148      72.000000             35        0  33.6
2026-10-23            1       85      66.000000             29        0  26.6
2027-10-23            8      183      64.000000              0        0  23.3
2028-10-23            1       89      51.178982             23       94  28.1
2029-10-23            0      137      38.392994             35      168  43.1
2030-10-23            5      116      25.607006              0        0  25.6
2031-10-23            3       78      12.821018             32       88  31.0
2032-10-23           10      115       0.000000              0        0  35.3
2033-10-23            2      197      70.000000             45      543  30.5
2034-10-23            8      125      96.000000              0        0   0.0
2035-10-23            4      110      92.000000              0        0  37.6
2036-10-23           10      168      74.000000              0        0  38.0

In [23]:
df.interpolate(method='polynomial',order=2)

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148      72.000000             35        0  33.6
2026-10-23            1       85      66.000000             29        0  26.6
2027-10-23            8      183      64.000000              0        0  23.3
2028-10-23            1       89      47.318881             23       94  28.1
2029-10-23            0      137      12.945917             35      168  43.1
2030-10-23            5      116     -31.288782              0        0  25.6
2031-10-23            3       78     -38.276682             32       88  31.0
2032-10-23           10      115       0.000000              0        0  35.3
2033-10-23            2      197      70.000000             45      543  30.5
2034-10-23            8      125      96.000000              0        0   0.0
2035-10-23            4      110      92.000000              0        0  37.6
2036-10-23           10      168      74.000000              0        0  38.0

In [24]:
df.interpolate(method='spline',order=2)

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148      72.000000             35        0  33.6
2026-10-23            1       85      66.000000             29        0  26.6
2027-10-23            8      183      64.000000              0        0  23.3
2028-10-23            1       89      46.587137             23       94  28.1
2029-10-23            0      137      13.738687             35      168  43.1
2030-10-23            5      116     -27.883969              0        0  25.6
2031-10-23            3       78     -34.479445             32       88  31.0
2032-10-23           10      115       0.000000              0        0  35.3
2033-10-23            2      197      70.000000             45      543  30.5
2034-10-23            8      125      96.000000              0        0   0.0
2035-10-23            4      110      92.000000              0        0  37.6
2036-10-23           10      168      74.000000              0        0  38.0

In [25]:
df

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89            NaN             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78            NaN             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [26]:
df.interpolate()

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89           51.2             23       94  28.1
2029-10-23            0      137           38.4             35      168  43.1
2030-10-23            5      116           25.6              0        0  25.6
2031-10-23            3       78           12.8             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [28]:
df.dtypes

Pregnancies        int64
Glucose            int64
BloodPressure    float64
SkinThickness      int64
Insulin            int64
BMI              float64
dtype: object

In [29]:
df.interpolate(limit=1)

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89           51.2             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78            NaN             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [30]:
df.interpolate(limit=2)

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89           51.2             23       94  28.1
2029-10-23            0      137           38.4             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78            NaN             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [32]:
df.interpolate(limit=1,limit_direction='backward')

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89            NaN             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78           12.8             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [33]:
df.interpolate(limit=2,limit_direction='backward')

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89            NaN             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116           25.6              0        0  25.6
2031-10-23            3       78           12.8             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [36]:
df.interpolate(limit=1,limit_direction='both')

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89           51.2             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78           12.8             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [37]:
df.interpolate(limit_area='inside')

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89           51.2             23       94  28.1
2029-10-23            0      137           38.4             35      168  43.1
2030-10-23            5      116           25.6              0        0  25.6
2031-10-23            3       78           12.8             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [38]:
df.interpolate(limit_area='outside')

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89            NaN             23       94  28.1
2029-10-23            0      137            NaN             35      168  43.1
2030-10-23            5      116            NaN              0        0  25.6
2031-10-23            3       78            NaN             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0

In [40]:
df.interpolate(inplace=True)
df

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
date
2025-10-23            6      148           72.0             35        0  33.6
2026-10-23            1       85           66.0             29        0  26.6
2027-10-23            8      183           64.0              0        0  23.3
2028-10-23            1       89           51.2             23       94  28.1
2029-10-23            0      137           38.4             35      168  43.1
2030-10-23            5      116           25.6              0        0  25.6
2031-10-23            3       78           12.8             32       88  31.0
2032-10-23           10      115            0.0              0        0  35.3
2033-10-23            2      197           70.0             45      543  30.5
2034-10-23            8      125           96.0              0        0   0.0
2035-10-23            4      110           92.0              0        0  37.6
2036-10-23           10      168           74.0              0        0  38.0